version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: luddite-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    networks:
      - luddite-network

  mongo-express:
    image: mongo-express:latest
    container_name: luddite-mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - luddite-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: luddite-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/luddite-launcher?authSource=admin
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    networks:
      - luddite-network

networks:
  luddite-network:
    driver: bridge

volumes:
  mongodb_data: